### ISSUE TITLE
这是什么意思

### ISSUE THREAD

**Issue by dmmdekkd** [TimeRainStarSky/Yunzai-QQBot-Plugin#15]
es/.pnpm/qq-group-bot@1.1.0/node_modul
es/qq-group-bot/lib/bot.js:410:24)\n' +
    '    at async sendMsg (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/QQBot-Pl
ugin/index.js:569:19)\n' +
    '    at async QQBotAdapter.sendMsg (file:///root/TRSS_AllBot/TRSS-Yunzai/plu
gins/QQBot-Plugin/index.js:590:9)\n' +
    '    at async e.reply (file'... 437 
more characters],
  [message]: 'request "/v2/users/DED2E68    '    at async QQBotAdapter.sendMsg (file:///root/TRSS_AllBot/TRSS-Yunzai/plu
gins/QQBot-Plugin/index.js:590:9)\n' +
    '    at async e.reply (file'... 437 
more characters],  [message]: 'request "/v2/users/DED2E68515BEB95B1F19FF5E3CA6E2B1/messages" error with code(340072): fetch markdown temp
late failed'
r with code(340072): fetch markdown temp
late failed'

这是什么意思

**Comment by TimeRainStarSky** [comment]
md模板有问题
