### ISSUE TITLE
配置QQ群Bot之后频道消息会连着回复两张图片

### ISSUE THREAD

**Issue by light0220** [TimeRainStarSky/Yunzai-QQBot-Plugin#16]
配置完QQ群Bot之后目前QQ群正常，但是频道会出现一个指令回复两张图片的问题
![image](https://github.com/user-attachments/assets/8acdd59b-7cc8-48a7-919d-098c501def31)
![image](https://github.com/user-attachments/assets/46ac9be7-b751-4051-bdd3-21209bdd6aef)

**Comment by TimeRainStarSky** [comment]
日志

**Comment by light0220** [comment]
> 日志

![image](https://github.com/user-attachments/assets/d914a8a7-d680-49ec-a62d-cb8cdb5388a4)

**Comment by TimeRainStarSky** [comment]
把频道插件删了
