### ISSUE TITLE
QQBot设置时报错接口访问源IP不在白名单

### ISSUE THREAD

**Issue by h-zhichao-w** [TimeRainStarSky/Yunzai-QQBot-Plugin#17]
使用`#QQBot设置`命令，但是返回错误信息
 [message]: 'request "/gateway/bot" error with code(11298): 接口访问源IP不在白名单
应该如何解决？

**Comment by TimeRainStarSky** [comment]
加白名单

**Comment by h-zhichao-w** [comment]
白名单里加入了还是不行

**Comment by FujishiroOtone** [comment]
> 加白名单

是要加入哪个ip进白名单？

**Comment by TimeRainStarSky** [comment]
> > 加白名单
> 
> 是要加入哪个ip进白名单？

https://baidu.com/s?wd=IP

**Comment by FujishiroOtone** [comment]
> > > 加白名单
> > 
> > 
> > 是要加入哪个ip进白名单？
> 
> https://baidu.com/s?wd=IP
> 
> 没有浏览器的话执行命令
> 
> ```
> curl -s ip.sb
> ```

谢谢，顺便问一下，如果我想把以前用icqq的记录内容复制过来给新的qq机器人使用的话，我复制config,data和plugins直接覆盖可以把以前的内容完全放在新建的qq机器人上吗

**Comment by TimeRainStarSky** [comment]
> 谢谢，顺便问一下，如果我想把以前用icqq的记录内容复制过来给新的qq机器人使用的话，我复制config,data和plugins直接覆盖可以把以前的内容完全放在新建的qq机器人上吗

不行，没有QQ号
