### ISSUE TITLE
机器人必须要是允许添加到群的公域机器人？

### ISSUE THREAD

**Issue by wdssfff00** [TimeRainStarSky/Yunzai-QQBot-Plugin#6]
如题。。。打扰了谢谢

**Comment by TimeRainStarSky** [comment]
目前是，之后会更新频道支持，现在频道用另一个插件

**Comment by devil233-ui** [comment]
> 目前是，之后会更新频道支持，现在频道用另一个插件

请问输完bot信息后【[Client]发生错误： 4014 intent无权限】也是这个原因么
